name: Comic
options:
  xcodeVersion: "16.0"
packages:
  WebParser:
    url: https://github.com/shinrenpan/WebParser
    from: 1.1.0
  AnyCodable:
    url: https://github.com/Flight-School/AnyCodable
    from: 0.6.7
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher
    from: 7.12.0
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    from: 1.19.0
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 18.0
    SWIFT_VERSION: 6.0
    DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: true
targets:
  Comic:
    platform: iOS
    type: application
    sources:
      - Sources
    settings:
      base:
        CODE_SIGN_STYLE: Manual
        INFOPLIST_FILE: Sources/App/Info.plist
        MARKETING_VERSION: 0.2.1
        CURRENT_PROJECT_VERSION: 20250425
        PRODUCT_BUNDLE_IDENTIFIER: com.shinrenpan.Comic
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: -Onone
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -O
    dependencies:
      - package: WebParser
      - package: AnyCodable
      - package: Kingfisher
      - package: ComposableArchitecture
